//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP_CarWorkshopService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Services
    {
        public int Service_ID { get; set; }
        public Nullable<int> Workshop_ID { get; set; }
        public Nullable<int> Car_ID { get; set; }
        public int Mileage { get; set; }
        public string Service_name { get; set; }
        public string Service_description { get; set; }
        public System.DateTime Service_date { get; set; }
    
        public virtual Car_Profiles Car_Profiles { get; set; }
        public virtual Workshop_Profiles Workshop_Profiles { get; set; }
    }
}
