//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP_CarWorkshopService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Profiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car_Profiles()
        {
            this.Car_Services = new HashSet<Car_Services>();
            this.Cars_followed = new HashSet<Cars_followed>();
        }
    
        public int Car_ID { get; set; }
        public Nullable<int> Brand_ID { get; set; }
        public string Car_model { get; set; }
        public string Car_VIN_number { get; set; }
        public int Car_production_year { get; set; }
        public Nullable<int> Car_first_registration_year { get; set; }
    
        public virtual Car_Brands Car_Brands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car_Services> Car_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars_followed> Cars_followed { get; set; }
    }
}
