//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP_CarWorkshopService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_followed
    {
        public int Car_follow_ID { get; set; }
        public Nullable<int> Car_profile_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
    
        public virtual Car_Profiles Car_Profiles { get; set; }
        public virtual Client_Profiles Client_Profiles { get; set; }
    }
}
