//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP_CarWorkshopService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITAPPCarWorkshopServiceDBEntities : DbContext
    {
        public ITAPPCarWorkshopServiceDBEntities()
            : base("name=ITAPPCarWorkshopServiceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car_Brands> Car_Brands { get; set; }
        public virtual DbSet<Car_Profiles> Car_Profiles { get; set; }
        public virtual DbSet<Car_Services> Car_Services { get; set; }
        public virtual DbSet<Cars_followed> Cars_followed { get; set; }
        public virtual DbSet<Client_Profiles> Client_Profiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Workshop_Brand_Connections> Workshop_Brand_Connections { get; set; }
        public virtual DbSet<Workshop_Comments> Workshop_Comments { get; set; }
        public virtual DbSet<Workshop_Employees> Workshop_Employees { get; set; }
        public virtual DbSet<Workshop_Opening_Hours> Workshop_Opening_Hours { get; set; }
        public virtual DbSet<Workshop_Profiles> Workshop_Profiles { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
