//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP_CarWorkshopService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public System.DateTime ReservationDateTime { get; set; }
        public string ReservationStatus { get; set; }
        public Nullable<int> Workshop_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Workshop_Profiles Workshop_Profiles { get; set; }
    }
}
