//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP_CarWorkshopService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop_Comments
    {
        public int Comment_ID { get; set; }
        public Nullable<int> Workshop_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public string Comment_description { get; set; }
        public double Comment_rating { get; set; }
        public System.DateTime Comment_date { get; set; }
    
        public virtual Client_Profiles Client_Profiles { get; set; }
        public virtual Workshop_Profiles Workshop_Profiles { get; set; }
    }
}
