//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP_CarWorkshopService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop_Opening_Hours
    {
        public int WOH_ID { get; set; }
        public Nullable<int> Workshop_ID { get; set; }
        public Nullable<System.TimeSpan> Mon_start { get; set; }
        public Nullable<System.TimeSpan> Mon_end { get; set; }
        public Nullable<System.TimeSpan> Tue_start { get; set; }
        public Nullable<System.TimeSpan> Tue_end { get; set; }
        public Nullable<System.TimeSpan> Wed_start { get; set; }
        public Nullable<System.TimeSpan> Wed_end { get; set; }
        public Nullable<System.TimeSpan> Thu_start { get; set; }
        public Nullable<System.TimeSpan> Thu_end { get; set; }
        public Nullable<System.TimeSpan> Fri_start { get; set; }
        public Nullable<System.TimeSpan> Fri_end { get; set; }
        public Nullable<System.TimeSpan> Sat_start { get; set; }
        public Nullable<System.TimeSpan> Sat_end { get; set; }
        public Nullable<System.TimeSpan> Sun_start { get; set; }
        public Nullable<System.TimeSpan> Sun_end { get; set; }
    
        public virtual Workshop_Profiles Workshop_Profiles { get; set; }
    }
}
