//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP_CarWorkshopService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop_Brand_Connections
    {
        public int WBC_ID { get; set; }
        public Nullable<int> Workshop_ID { get; set; }
        public Nullable<int> Car_brand_ID { get; set; }
    
        public virtual Car_Brands Car_Brands { get; set; }
        public virtual Workshop_Profiles Workshop_Profiles { get; set; }
    }
}
